// ============================================
// HARDCODED DATA - Auto-generated
// ============================================

const alphabetisationBiasData = [
  {
    "model_id": "gpt-4.1",
    "model_name": "GPT-4.1",
    "model_family": "openai",
    "is_reasoning": false,
    "control_eval_config": "gpt_4_1_april_25",
    "coordination_eval_config": "gpt_4_1_april_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 211,
    "control_converged_on_salient": 209,
    "control_converged_on_alphabetical": 2,
    "control_salient_pct": 99.1,
    "control_alphabetical_pct": 0.9,
    "control_salient_ci": 1.56,
    "control_differed_n": 189,
    "control_differed_both_first": 188,
    "control_differed_both_second": 1,
    "control_differed_first_pct": 99.5,
    "control_differed_second_pct": 0.5,
    "coordination_converged_n": 71,
    "coordination_converged_on_salient": 69,
    "coordination_converged_on_alphabetical": 2,
    "coordination_salient_pct": 97.2,
    "coordination_alphabetical_pct": 2.8,
    "coordination_salient_ci": 4.46,
    "coordination_differed_n": 329,
    "coordination_differed_both_first": 329,
    "coordination_differed_both_second": 0,
    "coordination_differed_first_pct": 100,
    "coordination_differed_second_pct": 0,
    "invalid_responses": 0,
    "date_tested": ""
  },
  {
    "model_id": "gpt-4.1-mini",
    "model_name": "GPT-4.1 Mini",
    "model_family": "openai",
    "is_reasoning": false,
    "control_eval_config": "gpt_4_1_mini_april_25",
    "coordination_eval_config": "gpt_4_1_mini_april_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 361,
    "control_converged_on_salient": 358,
    "control_converged_on_alphabetical": 3,
    "control_salient_pct": 99.2,
    "control_alphabetical_pct": 0.8,
    "control_salient_ci": 1.07,
    "control_differed_n": 39,
    "control_differed_both_first": 31,
    "control_differed_both_second": 8,
    "control_differed_first_pct": 79.5,
    "control_differed_second_pct": 20.5,
    "coordination_converged_n": 316,
    "coordination_converged_on_salient": 306,
    "coordination_converged_on_alphabetical": 10,
    "coordination_salient_pct": 96.8,
    "coordination_alphabetical_pct": 3.2,
    "coordination_salient_ci": 2,
    "coordination_differed_n": 84,
    "coordination_differed_both_first": 41,
    "coordination_differed_both_second": 43,
    "coordination_differed_first_pct": 48.8,
    "coordination_differed_second_pct": 51.2,
    "invalid_responses": 0,
    "date_tested": ""
  },
  {
    "model_id": "gpt-4.1-nano",
    "model_name": "GPT-4.1 Nano",
    "model_family": "openai",
    "is_reasoning": false,
    "control_eval_config": "gpt_4_1_nano_april_25",
    "coordination_eval_config": "gpt_4_1_nano_april_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 296,
    "control_converged_on_salient": 282,
    "control_converged_on_alphabetical": 14,
    "control_salient_pct": 95.3,
    "control_alphabetical_pct": 4.7,
    "control_salient_ci": 2.47,
    "control_differed_n": 104,
    "control_differed_both_first": 1,
    "control_differed_both_second": 103,
    "control_differed_first_pct": 1,
    "control_differed_second_pct": 99,
    "coordination_converged_n": 347,
    "coordination_converged_on_salient": 343,
    "coordination_converged_on_alphabetical": 4,
    "coordination_salient_pct": 98.8,
    "coordination_alphabetical_pct": 1.2,
    "coordination_salient_ci": 1.24,
    "coordination_differed_n": 53,
    "coordination_differed_both_first": 24,
    "coordination_differed_both_second": 29,
    "coordination_differed_first_pct": 45.3,
    "coordination_differed_second_pct": 54.7,
    "invalid_responses": 0,
    "date_tested": ""
  },
  {
    "model_id": "claude-opus-4.1",
    "model_name": "Claude Opus 4.1",
    "model_family": "anthropic",
    "is_reasoning": false,
    "control_eval_config": "opus_4_1_august_25",
    "coordination_eval_config": "opus_4_1_august_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 100,
    "control_converged_on_salient": 100,
    "control_converged_on_alphabetical": 0,
    "control_salient_pct": 100,
    "control_alphabetical_pct": 0,
    "control_salient_ci": 1.85,
    "control_differed_n": 300,
    "control_differed_both_first": 300,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 234,
    "coordination_converged_on_salient": 212,
    "coordination_converged_on_alphabetical": 22,
    "coordination_salient_pct": 90.6,
    "coordination_alphabetical_pct": 9.4,
    "coordination_salient_ci": 3.77,
    "coordination_differed_n": 94,
    "coordination_differed_both_first": 81,
    "coordination_differed_both_second": 13,
    "coordination_differed_first_pct": 86.2,
    "coordination_differed_second_pct": 13.8,
    "invalid_responses": 72,
    "date_tested": ""
  },
  {
    "model_id": "claude-opus-4.5",
    "model_name": "Claude Opus 4.5",
    "model_family": "anthropic",
    "is_reasoning": false,
    "control_eval_config": "opus_4_5_november_25",
    "coordination_eval_config": "opus_4_5_november_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 173,
    "control_converged_on_salient": 158,
    "control_converged_on_alphabetical": 15,
    "control_salient_pct": 91.3,
    "control_alphabetical_pct": 8.7,
    "control_salient_ci": 4.24,
    "control_differed_n": 227,
    "control_differed_both_first": 227,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 266,
    "coordination_converged_on_salient": 265,
    "coordination_converged_on_alphabetical": 1,
    "coordination_salient_pct": 99.6,
    "coordination_alphabetical_pct": 0.4,
    "coordination_salient_ci": 1.02,
    "coordination_differed_n": 134,
    "coordination_differed_both_first": 134,
    "coordination_differed_both_second": 0,
    "coordination_differed_first_pct": 100,
    "coordination_differed_second_pct": 0,
    "invalid_responses": 0,
    "date_tested": ""
  },
  {
    "model_id": "deepseek-v3",
    "model_name": "DeepSeek V3",
    "model_family": "deepseek",
    "is_reasoning": false,
    "control_eval_config": "deepseek_v3_march_25",
    "coordination_eval_config": "deepseek_v3_march_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 270,
    "control_converged_on_salient": 270,
    "control_converged_on_alphabetical": 0,
    "control_salient_pct": 100,
    "control_alphabetical_pct": 0,
    "control_salient_ci": 0.7,
    "control_differed_n": 130,
    "control_differed_both_first": 130,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 68,
    "coordination_converged_on_salient": 68,
    "coordination_converged_on_alphabetical": 0,
    "coordination_salient_pct": 100,
    "coordination_alphabetical_pct": 0,
    "coordination_salient_ci": 2.67,
    "coordination_differed_n": 332,
    "coordination_differed_both_first": 332,
    "coordination_differed_both_second": 0,
    "coordination_differed_first_pct": 100,
    "coordination_differed_second_pct": 0,
    "invalid_responses": 0,
    "date_tested": ""
  },
  {
    "model_id": "deepseek-v3.2-exp-thinking",
    "model_name": "DeepSeek V3.2-exp (thinking)",
    "model_family": "deepseek",
    "is_reasoning": true,
    "control_eval_config": "deepseek_v3_2_exp_october_25",
    "coordination_eval_config": "deepseek_v3_2_exp_reasoning_october_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 97,
    "control_converged_on_salient": 84,
    "control_converged_on_alphabetical": 13,
    "control_salient_pct": 86.6,
    "control_alphabetical_pct": 13.4,
    "control_salient_ci": 6.79,
    "control_differed_n": 303,
    "control_differed_both_first": 303,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 382,
    "coordination_converged_on_salient": 0,
    "coordination_converged_on_alphabetical": 382,
    "coordination_salient_pct": 0,
    "coordination_alphabetical_pct": 100,
    "coordination_salient_ci": 0.5,
    "coordination_differed_n": 16,
    "coordination_differed_both_first": 13,
    "coordination_differed_both_second": 3,
    "coordination_differed_first_pct": 81.2,
    "coordination_differed_second_pct": 18.8,
    "invalid_responses": 2,
    "date_tested": ""
  },
  {
    "model_id": "claude-haiku-4.5-thinking",
    "model_name": "Claude Haiku 4.5 (thinking)",
    "model_family": "anthropic",
    "is_reasoning": true,
    "control_eval_config": "haiku_4_5_october_25",
    "coordination_eval_config": "haiku_4_5_thinking_october_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 124,
    "control_converged_on_salient": 124,
    "control_converged_on_alphabetical": 0,
    "control_salient_pct": 100,
    "control_alphabetical_pct": 0,
    "control_salient_ci": 1.5,
    "control_differed_n": 276,
    "control_differed_both_first": 276,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 343,
    "coordination_converged_on_salient": 7,
    "coordination_converged_on_alphabetical": 336,
    "coordination_salient_pct": 2,
    "coordination_alphabetical_pct": 98,
    "coordination_salient_ci": 1.58,
    "coordination_differed_n": 57,
    "coordination_differed_both_first": 47,
    "coordination_differed_both_second": 10,
    "coordination_differed_first_pct": 82.5,
    "coordination_differed_second_pct": 17.5,
    "invalid_responses": 0,
    "date_tested": ""
  },
  {
    "model_id": "claude-opus-4.5-thinking",
    "model_name": "Claude Opus 4.5 (thinking)",
    "model_family": "anthropic",
    "is_reasoning": true,
    "control_eval_config": "opus_4_5_november_25",
    "coordination_eval_config": "opus_4_5_thinking_november_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 400,
    "control_converged_n": 173,
    "control_converged_on_salient": 158,
    "control_converged_on_alphabetical": 15,
    "control_salient_pct": 91.3,
    "control_alphabetical_pct": 8.7,
    "control_salient_ci": 4.24,
    "control_differed_n": 227,
    "control_differed_both_first": 227,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 343,
    "coordination_converged_on_salient": 6,
    "coordination_converged_on_alphabetical": 337,
    "coordination_salient_pct": 1.7,
    "coordination_alphabetical_pct": 98.3,
    "coordination_salient_ci": 1.48,
    "coordination_differed_n": 57,
    "coordination_differed_both_first": 49,
    "coordination_differed_both_second": 8,
    "coordination_differed_first_pct": 86,
    "coordination_differed_second_pct": 14,
    "invalid_responses": 0,
    "date_tested": ""
  },
  {
    "model_id": "claude-opus-4.1-valid",
    "model_name": "Claude Opus 4.1 (excl. invalid)",
    "model_family": "anthropic",
    "is_reasoning": false,
    "control_eval_config": "opus_4_1_august_25",
    "coordination_eval_config": "opus_4_1_august_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 328,
    "control_converged_n": 90,
    "control_converged_on_salient": 90,
    "control_converged_on_alphabetical": 0,
    "control_salient_pct": 100,
    "control_alphabetical_pct": 0,
    "control_salient_ci": 1.85,
    "control_differed_n": 238,
    "control_differed_both_first": 238,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 234,
    "coordination_converged_on_salient": 212,
    "coordination_converged_on_alphabetical": 22,
    "coordination_salient_pct": 90.6,
    "coordination_alphabetical_pct": 9.4,
    "coordination_salient_ci": 3.77,
    "coordination_differed_n": 94,
    "coordination_differed_both_first": 81,
    "coordination_differed_both_second": 13,
    "coordination_differed_first_pct": 86.2,
    "coordination_differed_second_pct": 13.8,
    "invalid_responses": 0,
    "date_tested": "",
    "excludes_invalid": true
  },
  {
    "model_id": "deepseek-v3.2-exp-thinking-valid",
    "model_name": "DeepSeek V3.2-exp (thinking) (excl. invalid)",
    "model_family": "deepseek",
    "is_reasoning": true,
    "control_eval_config": "deepseek_v3_2_exp_october_25",
    "coordination_eval_config": "deepseek_v3_2_exp_reasoning_october_25",
    "dataset": "salient_alphabetical",
    "total_pairs": 398,
    "control_converged_n": 96,
    "control_converged_on_salient": 83,
    "control_converged_on_alphabetical": 13,
    "control_salient_pct": 86.6,
    "control_alphabetical_pct": 13.4,
    "control_salient_ci": 6.79,
    "control_differed_n": 302,
    "control_differed_both_first": 302,
    "control_differed_both_second": 0,
    "control_differed_first_pct": 100,
    "control_differed_second_pct": 0,
    "coordination_converged_n": 382,
    "coordination_converged_on_salient": 0,
    "coordination_converged_on_alphabetical": 382,
    "coordination_salient_pct": 0,
    "coordination_alphabetical_pct": 100,
    "coordination_salient_ci": 0.5,
    "coordination_differed_n": 16,
    "coordination_differed_both_first": 13,
    "coordination_differed_both_second": 3,
    "coordination_differed_first_pct": 81.2,
    "coordination_differed_second_pct": 18.8,
    "invalid_responses": 0,
    "date_tested": "",
    "excludes_invalid": true
  }
];

const additiveCoordinationData = [
  {
    "model_id": "gpt-4.1",
    "model_name": "GPT-4.1",
    "control_converged": 211,
    "control_differed": 189,
    "coord_pct": 3.7,
    "coord_ci": 2.82,
    "to_salient": 7,
    "to_alpha": 0,
    "to_first": 182,
    "to_second": 0,
    "is_thinking": false
  },
  {
    "model_id": "gpt-4.1-mini",
    "model_name": "GPT-4.1 Mini",
    "control_converged": 361,
    "control_differed": 39,
    "coord_pct": 61.5,
    "coord_ci": 14.61,
    "to_salient": 19,
    "to_alpha": 5,
    "to_first": 8,
    "to_second": 7,
    "is_thinking": false
  },
  {
    "model_id": "gpt-4.1-nano",
    "model_name": "GPT-4.1 Nano",
    "control_converged": 296,
    "control_differed": 104,
    "coord_pct": 73.1,
    "coord_ci": 8.41,
    "to_salient": 76,
    "to_alpha": 0,
    "to_first": 10,
    "to_second": 18,
    "is_thinking": false
  },
  {
    "model_id": "claude-opus-4.5",
    "model_name": "Claude Opus 4.5",
    "control_converged": 173,
    "control_differed": 227,
    "coord_pct": 49.3,
    "coord_ci": 6.45,
    "to_salient": 112,
    "to_alpha": 0,
    "to_first": 115,
    "to_second": 0,
    "is_thinking": false
  },
  {
    "model_id": "deepseek-v3",
    "model_name": "DeepSeek V3",
    "control_converged": 270,
    "control_differed": 130,
    "coord_pct": 1.5,
    "coord_ci": 2.51,
    "to_salient": 2,
    "to_alpha": 0,
    "to_first": 128,
    "to_second": 0,
    "is_thinking": false
  },
  {
    "model_id": "deepseek-v3.2-exp-thinking",
    "model_name": "DeepSeek V3.2-exp (thinking)",
    "control_converged": 97,
    "control_differed": 302,
    "coord_pct": 96,
    "coord_ci": 2.26,
    "to_salient": 0,
    "to_alpha": 290,
    "to_first": 10,
    "to_second": 2,
    "is_thinking": true
  },
  {
    "model_id": "claude-haiku-4.5-thinking",
    "model_name": "Claude Haiku 4.5 (thinking)",
    "control_converged": 124,
    "control_differed": 276,
    "coord_pct": 91.3,
    "coord_ci": 3.35,
    "to_salient": 0,
    "to_alpha": 252,
    "to_first": 21,
    "to_second": 3,
    "is_thinking": true
  },
  {
    "model_id": "claude-opus-4.5-thinking",
    "model_name": "Claude Opus 4.5 (thinking)",
    "control_converged": 173,
    "control_differed": 227,
    "coord_pct": 89,
    "coord_ci": 4.09,
    "to_salient": 1,
    "to_alpha": 201,
    "to_first": 20,
    "to_second": 5,
    "is_thinking": true
  }
];

const biasControlledData = [
  {
    "model_id": "gpt-4.1",
    "model_name": "GPT-4.1",
    "dataset": "salient_alphabetical",
    "coordination_pct": 3.7,
    "coordination_ci": 2.82,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1",
    "model_name": "GPT-4.1",
    "dataset": "mundane_dangerous",
    "coordination_pct": 13.7,
    "coordination_ci": 4.98,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1",
    "model_name": "GPT-4.1",
    "dataset": "random_emoji",
    "coordination_pct": 0.3,
    "coordination_ci": 0.8,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1",
    "model_name": "GPT-4.1",
    "dataset": "random_mixed",
    "coordination_pct": 14,
    "coordination_ci": 4.14,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-mini",
    "model_name": "GPT-4.1 Mini",
    "dataset": "salient_alphabetical",
    "coordination_pct": 61.5,
    "coordination_ci": 14.61,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-mini",
    "model_name": "GPT-4.1 Mini",
    "dataset": "mundane_dangerous",
    "coordination_pct": 34.2,
    "coordination_ci": 10.24,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-mini",
    "model_name": "GPT-4.1 Mini",
    "dataset": "random_emoji",
    "coordination_pct": 16.8,
    "coordination_ci": 5.87,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-mini",
    "model_name": "GPT-4.1 Mini",
    "dataset": "random_mixed",
    "coordination_pct": 43.1,
    "coordination_ci": 8.87,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-nano",
    "model_name": "GPT-4.1 Nano",
    "dataset": "salient_alphabetical",
    "coordination_pct": 73.1,
    "coordination_ci": 8.41,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-nano",
    "model_name": "GPT-4.1 Nano",
    "dataset": "mundane_dangerous",
    "coordination_pct": 57.7,
    "coordination_ci": 5.24,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-nano",
    "model_name": "GPT-4.1 Nano",
    "dataset": "random_emoji",
    "coordination_pct": 62.1,
    "coordination_ci": 5.48,
    "is_reasoning": false
  },
  {
    "model_id": "gpt-4.1-nano",
    "model_name": "GPT-4.1 Nano",
    "dataset": "random_mixed",
    "coordination_pct": 56.1,
    "coordination_ci": 7.17,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.1",
    "model_name": "Claude Opus 4.1",
    "dataset": "salient_alphabetical",
    "coordination_pct": 65.1,
    "coordination_ci": 6.01,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.1",
    "model_name": "Claude Opus 4.1",
    "dataset": "mundane_dangerous",
    "coordination_pct": 11.5,
    "coordination_ci": 3.69,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.1",
    "model_name": "Claude Opus 4.1",
    "dataset": "random_emoji",
    "coordination_pct": 8.4,
    "coordination_ci": 2.81,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.1",
    "model_name": "Claude Opus 4.1",
    "dataset": "random_mixed",
    "coordination_pct": 27.7,
    "coordination_ci": 5.82,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.5",
    "model_name": "Claude Opus 4.5",
    "dataset": "salient_alphabetical",
    "coordination_pct": 49.3,
    "coordination_ci": 6.45,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.5",
    "model_name": "Claude Opus 4.5",
    "dataset": "mundane_dangerous",
    "coordination_pct": 23.1,
    "coordination_ci": 6.76,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.5",
    "model_name": "Claude Opus 4.5",
    "dataset": "random_emoji",
    "coordination_pct": 4.3,
    "coordination_ci": 2.06,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.5",
    "model_name": "Claude Opus 4.5",
    "dataset": "random_mixed",
    "coordination_pct": 14.1,
    "coordination_ci": 3.55,
    "is_reasoning": false
  },
  {
    "model_id": "claude-sonnet-4.5",
    "model_name": "Claude Sonnet 4.5",
    "dataset": "salient_alphabetical",
    "coordination_pct": 55.1,
    "coordination_ci": 13.42,
    "is_reasoning": false
  },
  {
    "model_id": "claude-sonnet-4.5",
    "model_name": "Claude Sonnet 4.5",
    "dataset": "mundane_dangerous",
    "coordination_pct": 9.1,
    "coordination_ci": 3.93,
    "is_reasoning": false
  },
  {
    "model_id": "claude-sonnet-4.5",
    "model_name": "Claude Sonnet 4.5",
    "dataset": "random_emoji",
    "coordination_pct": 5.2,
    "coordination_ci": 2.8,
    "is_reasoning": false
  },
  {
    "model_id": "claude-sonnet-4.5",
    "model_name": "Claude Sonnet 4.5",
    "dataset": "random_mixed",
    "coordination_pct": 13.8,
    "coordination_ci": 4.85,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3",
    "model_name": "DeepSeek V3",
    "dataset": "salient_alphabetical",
    "coordination_pct": 1.5,
    "coordination_ci": 2.51,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3",
    "model_name": "DeepSeek V3",
    "dataset": "mundane_dangerous",
    "coordination_pct": 9.7,
    "coordination_ci": 4.56,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3",
    "model_name": "DeepSeek V3",
    "dataset": "random_emoji",
    "coordination_pct": 5.4,
    "coordination_ci": 2.62,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3",
    "model_name": "DeepSeek V3",
    "dataset": "random_mixed",
    "coordination_pct": 13,
    "coordination_ci": 3.72,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3.2-exp",
    "model_name": "DeepSeek V3.2-exp",
    "dataset": "salient_alphabetical",
    "coordination_pct": 19.1,
    "coordination_ci": 4.42,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3.2-exp",
    "model_name": "DeepSeek V3.2-exp",
    "dataset": "mundane_dangerous",
    "coordination_pct": 46.7,
    "coordination_ci": 8.72,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3.2-exp",
    "model_name": "DeepSeek V3.2-exp",
    "dataset": "random_emoji",
    "coordination_pct": 38,
    "coordination_ci": 6.8,
    "is_reasoning": false
  },
  {
    "model_id": "deepseek-v3.2-exp",
    "model_name": "DeepSeek V3.2-exp",
    "dataset": "random_mixed",
    "coordination_pct": 36.7,
    "coordination_ci": 5.52,
    "is_reasoning": false
  },
  {
    "model_id": "claude-haiku-4.5",
    "model_name": "Claude Haiku 4.5",
    "dataset": "salient_alphabetical",
    "coordination_pct": 10.9,
    "coordination_ci": 3.69,
    "is_reasoning": false
  },
  {
    "model_id": "claude-haiku-4.5",
    "model_name": "Claude Haiku 4.5",
    "dataset": "mundane_dangerous",
    "coordination_pct": 15.8,
    "coordination_ci": 6.52,
    "is_reasoning": false
  },
  {
    "model_id": "claude-haiku-4.5",
    "model_name": "Claude Haiku 4.5",
    "dataset": "random_emoji",
    "coordination_pct": 2.1,
    "coordination_ci": 1.66,
    "is_reasoning": false
  },
  {
    "model_id": "claude-haiku-4.5",
    "model_name": "Claude Haiku 4.5",
    "dataset": "random_mixed",
    "coordination_pct": 1.9,
    "coordination_ci": 1.64,
    "is_reasoning": false
  },
  {
    "model_id": "claude-opus-4.5-thinking",
    "model_name": "Claude Opus 4.5 (thinking)",
    "dataset": "salient_alphabetical",
    "coordination_pct": 89,
    "coordination_ci": 4.09,
    "is_reasoning": true
  },
  {
    "model_id": "claude-opus-4.5-thinking",
    "model_name": "Claude Opus 4.5 (thinking)",
    "dataset": "mundane_dangerous",
    "coordination_pct": 60.5,
    "coordination_ci": 7.8,
    "is_reasoning": true
  },
  {
    "model_id": "claude-opus-4.5-thinking",
    "model_name": "Claude Opus 4.5 (thinking)",
    "dataset": "random_emoji",
    "coordination_pct": 80.1,
    "coordination_ci": 3.95,
    "is_reasoning": true
  },
  {
    "model_id": "claude-opus-4.5-thinking",
    "model_name": "Claude Opus 4.5 (thinking)",
    "dataset": "random_mixed",
    "coordination_pct": 74.8,
    "coordination_ci": 4.41,
    "is_reasoning": true
  }
];

